# Generated by Django 5.1.6 on 2025-02-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
